# ===================================================
# H2 Database 설정
# ===================================================
spring.datasource.url=jdbc:h2:mem:dietdb  
# 메모리에 dietdb라는 이름의 데이터베이스를 만들어줘
spring.datasource.driverClassName=org.h2.Driver
# H2 데이터베이스 드라이버 지정
spring.datasource.username=sa
spring.datasource.password=
# H2 기본 계정

# ===================================================
# JPA 설정 ─ Entity를 기반으로 테이블 자동 생성
# ===================================================
spring.jpa.hibernate.ddl-auto=update
# create: 매번 삭제 후 새로 생성
# create-drop: 종료하면 삭제
# update: 현재 테이블 유지하면서 변경사항만 적용

# ===================================================
# SQL 출력
# ===================================================
spring.jpa.show-sql=true
# 서버 실행 시 콘솔에 SQL문 출력
spring.jpa.properties.hibernate.format_sql=true
# SQL을 보기 좋은 형태로 출력
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# SQL의 ? 자리에 바인딩되는 실제 파라미터 값 확인

# ===================================================
# H2 콘솔
# ===================================================
spring.h2.console.enabled=true
# 콘솔 접속을 원할 경우 http://localhost:8080/h2-console

# ===================================================
# 문자 인코딩 설정
# ===================================================
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
# HTTP 요청과 응답의 문자 인코딩 설정